<style global>
    table {
        border-spacing: 0;
        border-top: 1px solid black;
        border-left: 1px solid black;
    }
    th,
    td {
        border-bottom: 1px solid black;
        border-right: 1px solid black;
        padding: 0.5rem;
    }

    th {
        position: relative;
    }

    th .resizer {
        position: absolute;
        top: 0;
        bottom: 0;
        right: -4px;
        width: 8px;
        z-index: 1;
        background: rgba(200, 200, 200, 0.5);
        cursor: col-resize;
    }
    .sorted {
        background: rgb(144, 191, 148, 0.5);
    }
    .matches {
        font-weight: 700;
    }
    .group {
        background: rgb(144, 191, 148, 0.5);
    }
    .aggregate {
        background: rgb(238, 212, 100, 0.5);
    }
    .repeat {
        background: rgb(255, 139, 139, 0.5);
    }
    .selected {
        background: rgb(148, 205, 255, 0.5);
    }
    .virtual-list-wrapper {
    }
    tbody {
        display: flex;
        width: 100%;
    }
</style>

<script>
    import { readable } from 'svelte/store';
    import { Render, Subscribe, createTable } from 'svelte-headless-table';

    import VirtualList from 'svelte-tiny-virtual-list';
    const data = readable([
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
        { name: 'Ada Lovelace', age: 21 },
        { name: 'Barbara Liskov', age: 52 },
        { name: 'Richard Hamming', age: 38 },
    ]);

    const table = createTable(data);

    const columns = table.createColumns([
        table.column({
            header: 'Name',
            accessor: 'name',
        }),
        table.column({
            header: 'Age',
            accessor: 'age',
        }),
    ]);
    const { headerRows, rows, tableAttrs } = table.createViewModel(columns);
</script>

<table {...$tableAttrs}>
    <thead>
        {#each $headerRows as headerRow (headerRow.id)}
            <Subscribe rowAttrs="{headerRow.attrs()}" let:rowAttrs>
                <tr {...rowAttrs}>
                    {#each headerRow.cells as cell (cell.id)}
                        <Subscribe attrs="{cell.attrs()}" let:attrs>
                            <th {...attrs}>
                                <Render of="{cell.render()}" />
                            </th>
                        </Subscribe>
                    {/each}
                </tr>
            </Subscribe>
        {/each}
    </thead><tbody class="tbody">
        <VirtualList width="100%" height="{600}" itemCount="{$rows.length}" itemSize="{50}">
            <svelte:fragment slot="item" let:index let:style>
                {@const row = $rows[index]}
                <tr style="{style}" {...row.attrs()}>
                    <Subscribe rowAttrs="{row.attrs()}">
                        {#each row.cells as cell (cell.id)}
                            <Subscribe attrs="{cell.attrs()}" let:attrs>
                                <td {...attrs}>
                                    <Render of="{cell.render()}" />
                                </td>
                            </Subscribe>
                        {/each}
                    </Subscribe>
                </tr>
            </svelte:fragment>
        </VirtualList>
    </tbody>
</table>
